### ISSUE TITLE
Kindly suggestions

### ISSUE THREAD

**Issue by sambeck87** [luigirazum/mv-devweek#2]
You are doing a great job so far, but we have some friendly suggestions to improve your web page:

- We suggest you put your main nav inside a div to correctly manage the margins and centralize it properly.
- You could change the size of the icons of your navbar, They look great with another size.

@maher @sambeck87 @Juanpa8830

**Comment by luigirazum** [comment]
### Thanks a lot for your suggestions 👍...
### After making the changes this is how the navbar looks like.... ✔

![image](https://user-images.githubusercontent.com/67355479/204052516-24b435d6-3f74-4a2f-bd79-1ebc0074c972.png)

#### If there are no further comments 💬 about the applied changes 👨‍💻, I will close this issue in ⏰ 48 hours.

**Comment by luigirazum** [comment]
After applying the suggested changes, no further comments have been received. So, this issue will be closed.
